### ISSUE TITLE
Release Radar Plugin Not Fetching Anything

### ISSUE THREAD

**Issue by Kotaless** [bertigert/DeezMod#1]
Hello,
Thank you for this mod and the plugins. 
Release Radar Plugin works very well in my browser, but it doesn't work in the desktop app. 
I tried clean app install (6.0.250) and full/normal DeezMod installs, but it didn't work.

![image](https://github.com/user-attachments/assets/ade41074-ff35-4709-9984-1f34f0fac4f6)
![image](https://github.com/user-attachments/assets/ff3557bf-9a92-4139-a055-c6050991ae00)

**Comment by bertigert-2** [comment]
if you look at the network tab, are any requests to 
https://www.deezer.com/ajax/gw-light.php?method=song.getListByAlbum
and 
 https://pipe.deezer.com/api
 being made? It should look similar to this
 
![image](https://github.com/user-attachments/assets/78e84dcf-fb4f-4027-82b5-022487fd74e7)

 
 I will implement better logging in the future.

**Comment by Kotaless** [comment]
> if you look at the network tab, are any requests to https://www.deezer.com/ajax/gw-light.php?method=song.getListByAlbum and https://pipe.deezer.com/api being made? It should look similar to this

I see 1 pipe.deezer.com/api but no song.getListByAlbum.

**Comment by bertigert-2** [comment]
Really weird, can you send a screenshot of your settings? Also, you should be careful with sharing the requests, you sent your apikey which can be used to do bad stuff.

**Comment by Kotaless** [comment]
> Really weird, can you send a screenshot of your settings? Also, you should be careful with sharing the requests, you sent your apikey which can be used to do bad stuff.

Thanks for the warning. I haven't changed the settings.
![image](https://github.com/user-attachments/assets/42ea9519-3c68-4a36-8047-f513a556f28e)

**Comment by bertigert-2** [comment]
I've implemented more logging in the latest [version](https://github.com/bababoi-2/DeezMod/blob/main/plugins/release_radar.js). redownload that, and also try deleting "release_radar_config" and "release_radar_cache" from the localstorage. I will implement a UI for that later on. Send me a screenshot of the debugs in the console (you need to enable the debug level in the console)

**Comment by Kotaless** [comment]
> I've implemented more logging in the latest [version](https://github.com/bababoi-2/DeezMod/blob/main/plugins/release_radar.js). redownload that, and also try deleting "release_radar_config" and "release_radar_cache" from the localstorage. I will implement a UI for that later on. Send me a screenshot of the debugs in the console (you need to enable the debug level in the console)

"1.2.3-dev" is working, thank you!
![image](https://github.com/user-attachments/assets/20144ac9-1937-405e-9b6b-0659e3f17ead)
Just to be sure I reverted back to "1.2.2" and yellow again. I believe beside logging you made some changes.
![image](https://github.com/user-attachments/assets/a95bdfd6-9439-4394-a102-f48e4cfc433b)
